### ISSUE TITLE
what's the meaning and how to generates the file candidate_release-f-to-i.csv & candidate_release-i-to-f.csv

### ISSUE THREAD

**Issue by SeekPoint** [google/categorybuilder#8]

**Comment by amahabal** [comment]
These two are matrices mapping items to contexts and vice versa (two because they are asymmetric and not mere transposes). The details are in the paper: https://www.aclweb.org/anthology/S18-2031.pdf.

Sorry for the late reply: I left Google and did not realize I stopped getting bug reports from here.

Thanks,
  Abhijit
